parameters:

services:
    core.memcached:
        class: Acilia\Component\Memcached\Service\MemcachedService
        arguments: [%memcached.servers%, %kernel.environment%, %kernel.debug%, %memcached.prefix%, %memcached.enabled%]

    core.fragment_cache.listener:
        class: Acilia\Component\FragmentCache\EventListener\FragmentCacheListener
        arguments: [@event_dispatcher, %kernel.environment%, %kernel.debug%, %fragment_cache.enabled%, @core.memcached]
        tags:
            - { name: kernel.event_subscriber }
